ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS loyalty_points INTEGER NOT NULL DEFAULT 0;

ALTER TABLE tenant_settings
  ADD COLUMN IF NOT EXISTS loyalty_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS loyalty_points_per_unit INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS loyalty_point_value DECIMAL(10,4) NOT NULL DEFAULT 0.01;

ALTER TABLE tenant_settings
  ADD COLUMN IF NOT EXISTS daily_sales_target DECIMAL(15,4) NOT NULL DEFAULT 0;
